version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.21-node
    steps:
      - checkout
      - restore_cache:
          key: v1-composer-{{ checksum "composer.json" }}
      - run:
          name: Install composer dependencies
          command: composer install --no-interaction --prefer-dist
      - save_cache:
          key: v1-composer-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}
      - run:
          name: Install node_modules dependencies
          command: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: circleci/php:7.4.21-node-browsers
        environment:
          APP_ENV: testing
          DB_CONNECTION: circle_test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: update apt-get
          command: sudo apt-get update
      - run:
          name: pdo_mysql install
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: run phpunit
          command: vendor/bin/phpunit

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
